version: "3.9"
services:
  db:
    image: postgres:16
    container_name: postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_local
      POSTGRES_PASSWORD: parola_local
      POSTGRES_DB: baza_local
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
